# Change these first
owner: GZod01 # Your GitHub organization or username, where this repository lives
repo: gzod01-server-uptime # The name of this repository

sites:
  - name: Sezille.net Main Server
    slug: sezille-net
    url: https://sezille.net
    maxRedirects: 10
  - name: CyberGammaGroup Websites VM
    slug: cybergammagroup-websites-vm
    url: websites.vm.cybergamma.group
    ####check: "tcp-ping"
    ####ipv6: true
    maxRedirects: 10
  - name: CyberGammaGroup
    slug: cybergamma-group
    url: https://cybergamma.group
    maxRedirects: 10
  - name: CyberGammApps
    slug: cybergammapps
    url: https://apps.cybergamma.group
    maxRedirects: 10
  - name: CyberGammaForge VM
    slug: cybergammaforge-vm
    url: forge.vm.cybergamma.group
    ####check: "tcp-ping"
    ####ipv6: true
    maxRedirects: 10
  - name: CyberGammaForge
    slug: cybergammaforge
    url: https://forge.cybergamma.group
    maxRedirects: 10
  - name: CyberGammaGroup Communications VM
    slug: cybergammagroup-communications-vm
    url: comm.vm.cybergamma.group
    ####check: "tcp-ping"
    ####ipv6: true
    maxRedirects: 10
  - name: CyberGammaMail
    slug: cybergammamail
    url: https://mail.cybergamma.group
    maxRedirects: 10
  - name: CyberGammaChat
    slug: cybergammachat
    url: https://ess.cybergamma.group
    maxRedirects: 10
  - name: CyberGammaGroup Services VM
    slug: cybergammagroup-services-vm
    url: services.vm.cybergamma.group
    ####check: "tcp-ping"
    ####ipv6: true
    maxRedirects: 10
  - name: CyberGammaCloud
    slug: cybergammacloud
    url: https://nc.cybergamma.group
    maxRedirects: 10
  - name: Home Assistant Sezille.net VM
    slug: home-assistant-sezille-net-vm
    url: https://haos.sezille.net
    maxRedirects: 10
  - name: Home Assistant Sezille.net
    slug: home-assistant-sezille-net
    url: https://haos.sezille.net
    maxRedirects: 10


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.gh.gzod01.fr
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CyberGamma.Group Server Uptime
  introTitle: "CyberGamma.Group Server Uptime Monitor powered by Upptime"
  introMessage: Status page for cybergamm.group server and all subdomains and other site hosted on cybergamm.group server
  navbar:
    - title: Status
      href: /
    - title: Sezille.net
      href: https://sezille.net
    - title: CyberGamma.Group
      href: https://cybergamma.group
    - title: GZod01.FR
      href: https://gzod01.fr
    
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
