# Change these first
owner: GZod01 # Your GitHub organization or username, where this repository lives
repo: gzod01-server-uptime # The name of this repository

sites:
  - name: GZod01.fr
    url: https://gzod01.fr
  - name: IGSTV.GZod01.fr
    url: https://igstv.gzod01.fr
  - name: Syllchips.GZod01.fr
    url: https://syllchips.gzod01.fr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.gh.gzod01.fr
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: GZod01.fr Server Uptime
  introTitle: "GZod01.fr Server Uptime Monitor powered by Upptime"
  introMessage: Status page for GZod01.fr server and all subdomains and other site hosted on GZod01.fr server
  navbar:
    - title: Status
      href: /
    - title: GZod01.fr
      href: https://gzod01.fr
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
