# Change these first
owner: GZod01 # Your GitHub organization or username, where this repository lives
repo: gzod01-server-uptime # The name of this repository

sites:
  - name: cybergamm.group
    url: https://cybergamm.group
    maxRedirects: 10
  - name: IGSTV.cybergamm.group
    url: https://igstv.cybergamma.group
    maxRedirects: 10
  - name: Syllchips.cybergamm.group
    url: https://syllchips.cybergamma.group
    maxRedirects: 10
  - name: OiseauK.cybergamm.group
    url: https://oiseauk.cybergamma.group
    maxRedirects: 10
  - name: APPS.cybergamm.group (CyberGammApps)
    url: https://apps.cybergamm.group
    maxRedirects: 10
  - name: Forge.cybergamm.group (CyberGammaForge)
    url: https://forge.cybergamm.group
    maxRedirects: 10
  - name: Mail.cybergamm.group (CyberGammaMail)
    url: https://mail.cybergamm.group
    maxRedirects: 10
  - name: Stellae-Auri.cybergamm.group (Stellae Auri Website)
    url: https://stellae-auri.cybergamm.group
    maxRedirects: 10

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.gh.cybergamm.group
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: cybergamm.group Server Uptime
  introTitle: "cybergamm.group Server Uptime Monitor powered by Upptime"
  introMessage: Status page for cybergamm.group server and all subdomains and other site hosted on cybergamm.group server
  navbar:
    - title: Status
      href: /
    - title: cybergamm.group
      href: https://cybergamm.group
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
