# Change these first
owner: GZod01 # Your GitHub organization or username, where this repository lives
repo: gzod01-server-uptime # The name of this repository

sites:
  - name: Sézille.Net
    url: https://sezille.net
    maxRedirects: 10
  - name: CyberGamma.Group
    url: https://CyberGamma.group
    slug: cybergamma-group
    maxRedirects: 10
  - name: Gzod01.Fr
    url: https://gzod01.fr
  - name: IGSTV.gzod01.fr
    url: https://igstv.gzod01.fr
    maxRedirects: 10
  - name: Chips.CyberGamma.group (SyllChips website)
    url: https://chips.cybergamma.group
    maxRedirects: 10
  - name: CyberGammApps
    slug: cybergammapps
    url: https://apps.cybergamma.group
    maxRedirects: 10
  - name: CyberGammaForge
    slug: cybergammaforge
    url: https://forge.cybergamma.group
    maxRedirects: 10
  - name: Mail.cybergamma.group (CyberGammaMail)
    url: https://mail.cybergamma.group
    maxRedirects: 10
  - name: Stellae-Auri.cybergamma.group (Stellae Auri Website)
    url: https://stellae-auri.cybergamma.group
    maxRedirects: 10
  - name: Test
    url: https://budget.cybergamma.group
    maxRedirects: 9


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.gh.gzod01.fr
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CyberGamma.Group Server Uptime
  introTitle: "CyberGamma.Group Server Uptime Monitor powered by Upptime"
  introMessage: Status page for cybergamm.group server and all subdomains and other site hosted on cybergamm.group server
  navbar:
    - title: Status
      href: /
    - title: CyberGamma.Group
      href: https://cybergamma.group
    - title: GZod01.FR
      href: https://gzod01.fr
    - title: Sezille.net
      href: https://sezille.net
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
